name: Deploy

on:
  push:
    branches:
      - master  # Use your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'false'  # Disables recursive submodule checkout

      - name: Remove problematic nested submodule
        run: |
          # Remove the nested submodule folder if it's not required
          rm -rf build/script_interpreter/ripemd160

      - name: Build project
        run: |
          echo "Building project..."
          # Add your actual build commands here
