name: Deploy

on:
  push:
    branches:
      - master  # Updated to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'false'  # Disable submodules; using string form for extra clarity

      - name: Build project
        run: |
          echo "Building project..."
          # Add your actual build commands here
